# This file is part of ABEL
# Copyright 2025, The ABEL Authors
# Authors: C.A.Lindstrøm(1), J.B.B.Chen(1), O.G.Finnerud(1), D.Kalvik(1), E.Hørlyk(1), A.Huebl(2), K.N.Sjobak(1), E.Adli(1)
# Affiliations: 1) University of Oslo, 2) LBNL
# License: GPL-3.0-or-later

# Config file for ABEL installation, in TOML format
# Don't modify this file directly, as it is tracked with GIT.
# To customise the defaults, please modify the personal ~/.abelconfig.toml, 
# as this copy will then take precedence (as specified in CONFIG.py::CONFIG.config_searchpath).
#
# TOML file format: https://toml.io/en/
# Python library used to read this file: https://docs.python.org/3/library/tomllib.html#module-tomllib
#
# This is default abelconfig.toml version 1, 19/11/2024, K. Sjobak
#

[cluster] # COMPUTE CLUSTER CONFIGURATION

cluster_name = "LOCAL" # Set to lumi/betzy/LOCAL/etc
project_name = "your_project_number_here"

#Normally these variables are autoset by CONFIG.py based on cluster_name,
# but can also override them here
# partition_name_standard = "standard-g"
# partition_name_small = "small-g"

[defaults] # ABEL STANDARD VALUES

# plot width defaults
plot_fullwidth_default = 18 # [cm]
plot_width_default     =  8 # [cm]

# default colormap
default_cmap = "FLASHForward"

[directories] ## ABEL DIRECTORIES

#  In this file, paths can be listed as "strings" or 'literal strings',
#  or [arrays, of, elements] where elements can be (literal) strings.
#  In arrays, literal strings can be keywords, which start with a $.
#  Currently valid choices are
#  '$run_data_path', '$software_path', '$hipace_path'.
#  Additionally environment variables such as HOME ($HOME in bash) can be referenced by using $$, i.e.
#  '$$HOME', '$Lumi_something'.
#  The elements of the arrays are joined together by os.path.join()

run_data_path  = 'run_data/'                 # path to tracking data directory
temp_path      = ['$run_data_path', 'temp/'] # temporary directory

[external_codes] ## SETUP OF COUPLING TO EXTERNAL CODES

#software_path  = '/your/project/path/here' #Common software path
software_path  = ['$$HOME', 'code']

[external_codes.elegant] # Configuration for ELEGANT

elegant_use_container = false  # To use a contiainer or not. Valid values are true and false.
elegant_path   = ['$software_path', 'elegant', 'bin/']  # Path to elegant executable.
#elegant_path   = ['$software_path', 'elegant']  # Path to elegant.sif file. Use if elegant_use_container is true.

bind_path      = '/pfs/lustrep2/scratch/project_000000000' # Only used if elegant_use_container is true
# elegant_exec    = ''  #Autogenerated by CONFIG.py based on elegant_use_container, can override here
# elegant_rpnflag = ''  #Autogenerated based on elegant_use_container, can override here
# elegant_is_installed = True  #Autogenerated based on whether CONFIG.py can find the ELEGANT executable or .sif. Can override here.

[external_codes.hipace] #Configuration for HIPACE++
hipace_path    = ['$software_path', 'hipace']
hipace_binary  = ['$hipace_path', 'build', 'bin', 'hipace']

[external_codes.guineapig] #Configuration for GUINEA-PIG
guineapig_path = ['$software_path', 'guineapig', 'bin'] # path to GUINEA-PIG directory


# Text files should end on a newline
